# Generated by Django 3.1.12 on 2021-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Dob',
            field=models.CharField(max_length=100),
        ),
    ]
